EncryptionDecryptionPOC/EncryptionDecryptionPOC/Controllers/EncryptionDecryptionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EncryptionDecryptionPOC.Controllers
{
    public class EncryptionDecryptionController : Controller
    {
        // GET: EncryptionDecryption
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Encrypt()
        {
            ViewBag.estring = null;
            return View();
        }

        [HttpPost]
        public ActionResult Encrypt(string encryptionstring)
        {
            SecurePasswordHasher objSecurePasswordHasher = new SecurePasswordHasher();
            string estring = objSecurePasswordHasher.Encrypt(encryptionstring);
            ViewBag.estring = estring;
            return View();
        }

        public ActionResult Decrypt()
        {
            ViewBag.dstring = null;
            return View();
        }

        [HttpPost]
        public ActionResult Decrypt(string decryptionstring)
        {
            SecurePasswordHasher objSecurePasswordHasher = new SecurePasswordHasher();
            string dstring = objSecurePasswordHasher.Decrypt(decryptionstring);
            ViewBag.dstring = dstring;
            return View();
        }
    }
}

EncryptionDecryptionPOC/EncryptionDecryptionPOC/Views/EncryptionDecryption/Decrypt.cshtml
@{
    ViewBag.Title = "Decrypt";
}

<h2>Decrypt</h2>
<div class="clearfix">&nbsp;</div>

@using (Html.BeginForm())
{
    if (ViewBag.dstring == null || ViewBag.dstring == "")
    {
        <input type=text name="decryptionstring" />
        <input type=submit value="Decrypt" />
    }
    else
    {
        <p> Your Encrypted string is : -  <span>&nbsp;</span> @ViewBag.dstring</p>
    }
}

EncryptionDecryptionPOC/EncryptionDecryptionPOC/Views/EncryptionDecryption/Encrypt.cshtml
@{
    ViewBag.Title = "Encrypt";
}

<h2>Encrypt</h2>
<div class="clearfix">&nbsp;</div>

@using (Html.BeginForm())
{
    if (ViewBag.estring == null || ViewBag.estring == "")
    {
        <input type=text name="encryptionstring" />
        <input type=submit value="Encrypt" />
    }
    else
    {
        <p> Your Encrypted string is : -  <span>&nbsp;</span> @ViewBag.estring</p>
    }
}

EncryptionDecryptionPOC/EncryptionDecryptionPOC/Views/EncryptionDecryption/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Encryption And Decryption</h2>

<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>

@Html.ActionLink("Encrypt", "Encrypt")
<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>
@Html.ActionLink("Decrypt", "Decrypt")

EncryptionDecryptionPOC/EncryptionDecryptionPOC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "EncryptionDecryption", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>